# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-06 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('url', models.URLField(unique=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('level', models.CharField(blank=True, choices=[('introductory', 'introductory'), ('intermediate', 'intermediate'), ('in-depth', 'in-depth')], default='introductory', max_length=30, verbose_name='Level of depth')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/%Y/%m/%d/')),
                ('image_thumbnail2', models.ImageField(blank=True, null=True, upload_to='resources/%Y/%m/%d/')),
                ('image_thumbnail3', models.ImageField(blank=True, null=True, upload_to='resources/%Y/%m/%d/')),
                ('video_upload', models.FileField(blank=True, null=True, upload_to='resources/%Y/%m/%d/')),
                ('video_embed', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_votes', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('rating_score', models.IntegerField(blank=True, default=0, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(default='purple', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='topics/%Y/%m/%d/')),
                ('official_website', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='courses.ResourceType'),
        ),
        migrations.AddField(
            model_name='resource',
            name='topics',
            field=models.ManyToManyField(to='courses.Topic'),
        ),
        migrations.AddField(
            model_name='featuredresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='featuredresource',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ResourceType'),
        ),
        migrations.AddField(
            model_name='featuredresource',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='featuredresource',
            unique_together=set([('topic', 'resource_type')]),
        ),
    ]
